#!/bin/sh
PROJ_DIR="$HOME/.proj"

if [ ! -z "$PROJ_HOME" ]; then
  PROJ_DIR=$PROJ_HOME
fi

PROJ_DATA_DIR="$PROJ_DIR"
PROJ_BIN_DIR="$PROJ_DIR/bin"

sh "$PROJ_DIR/bin/cli" $PROJ_BIN_DIR $PROJ_DATA_DIR $@
